# Generated by Django 6.1.1 on 2026-10-01 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_multilingual_song_versions'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quizquestion',
            name='unique_question_order_in_song',
        ),
        migrations.AlterField(
            model_name='annotation',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='main.quizsong', verbose_name='Версия песни'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.quizsong', verbose_name='Версия песни'),
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.UniqueConstraint(fields=('song', 'order'), name='unique_question_order_in_song_version'),
        ),
    ]
